name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose 

      - name: Docker Build
        run: |
          docker-compose build

      - name: Run migrations
        run: |
          docker-compose run web python manage.py migrate

      - name: Run tests
        run: |
          docker-compose run web python manage.py test api_rest
